################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../grlib/fonts/fontcm12.c \
../grlib/fonts/fontcm12b.c \
../grlib/fonts/fontcm12i.c \
../grlib/fonts/fontcm14.c \
../grlib/fonts/fontcm14b.c \
../grlib/fonts/fontcm14i.c \
../grlib/fonts/fontcm16.c \
../grlib/fonts/fontcm16b.c \
../grlib/fonts/fontcm16i.c \
../grlib/fonts/fontcm18.c \
../grlib/fonts/fontcm18b.c \
../grlib/fonts/fontcm18i.c \
../grlib/fonts/fontcm20.c \
../grlib/fonts/fontcm20b.c \
../grlib/fonts/fontcm20i.c \
../grlib/fonts/fontcm22.c \
../grlib/fonts/fontcm22b.c \
../grlib/fonts/fontcm22i.c \
../grlib/fonts/fontcm24.c \
../grlib/fonts/fontcm24b.c \
../grlib/fonts/fontcm24i.c \
../grlib/fonts/fontcm26.c \
../grlib/fonts/fontcm26b.c \
../grlib/fonts/fontcm26i.c \
../grlib/fonts/fontcm28.c \
../grlib/fonts/fontcm28b.c \
../grlib/fonts/fontcm28i.c \
../grlib/fonts/fontcm30.c \
../grlib/fonts/fontcm30b.c \
../grlib/fonts/fontcm30i.c \
../grlib/fonts/fontcm32.c \
../grlib/fonts/fontcm32b.c \
../grlib/fonts/fontcm32i.c \
../grlib/fonts/fontcm34.c \
../grlib/fonts/fontcm34b.c \
../grlib/fonts/fontcm34i.c \
../grlib/fonts/fontcm36.c \
../grlib/fonts/fontcm36b.c \
../grlib/fonts/fontcm36i.c \
../grlib/fonts/fontcm38.c \
../grlib/fonts/fontcm38b.c \
../grlib/fonts/fontcm38i.c \
../grlib/fonts/fontcm40.c \
../grlib/fonts/fontcm40b.c \
../grlib/fonts/fontcm40i.c \
../grlib/fonts/fontcm42.c \
../grlib/fonts/fontcm42b.c \
../grlib/fonts/fontcm42i.c \
../grlib/fonts/fontcm44.c \
../grlib/fonts/fontcm44b.c \
../grlib/fonts/fontcm44i.c \
../grlib/fonts/fontcm46.c \
../grlib/fonts/fontcm46b.c \
../grlib/fonts/fontcm46i.c \
../grlib/fonts/fontcm48.c \
../grlib/fonts/fontcm48b.c \
../grlib/fonts/fontcm48i.c \
../grlib/fonts/fontcmsc12.c \
../grlib/fonts/fontcmsc14.c \
../grlib/fonts/fontcmsc16.c \
../grlib/fonts/fontcmsc18.c \
../grlib/fonts/fontcmsc20.c \
../grlib/fonts/fontcmsc22.c \
../grlib/fonts/fontcmsc24.c \
../grlib/fonts/fontcmsc26.c \
../grlib/fonts/fontcmsc28.c \
../grlib/fonts/fontcmsc30.c \
../grlib/fonts/fontcmsc32.c \
../grlib/fonts/fontcmsc34.c \
../grlib/fonts/fontcmsc36.c \
../grlib/fonts/fontcmsc38.c \
../grlib/fonts/fontcmsc40.c \
../grlib/fonts/fontcmsc42.c \
../grlib/fonts/fontcmsc44.c \
../grlib/fonts/fontcmsc46.c \
../grlib/fonts/fontcmsc48.c \
../grlib/fonts/fontcmss12.c \
../grlib/fonts/fontcmss12b.c \
../grlib/fonts/fontcmss12i.c \
../grlib/fonts/fontcmss14.c \
../grlib/fonts/fontcmss14b.c \
../grlib/fonts/fontcmss14i.c \
../grlib/fonts/fontcmss16.c \
../grlib/fonts/fontcmss16b.c \
../grlib/fonts/fontcmss16i.c \
../grlib/fonts/fontcmss18.c \
../grlib/fonts/fontcmss18b.c \
../grlib/fonts/fontcmss18i.c \
../grlib/fonts/fontcmss20.c \
../grlib/fonts/fontcmss20b.c \
../grlib/fonts/fontcmss20i.c \
../grlib/fonts/fontcmss22.c \
../grlib/fonts/fontcmss22b.c \
../grlib/fonts/fontcmss22i.c \
../grlib/fonts/fontcmss24.c \
../grlib/fonts/fontcmss24b.c \
../grlib/fonts/fontcmss24i.c \
../grlib/fonts/fontcmss26.c \
../grlib/fonts/fontcmss26b.c \
../grlib/fonts/fontcmss26i.c \
../grlib/fonts/fontcmss28.c \
../grlib/fonts/fontcmss28b.c \
../grlib/fonts/fontcmss28i.c \
../grlib/fonts/fontcmss30.c \
../grlib/fonts/fontcmss30b.c \
../grlib/fonts/fontcmss30i.c \
../grlib/fonts/fontcmss32.c \
../grlib/fonts/fontcmss32b.c \
../grlib/fonts/fontcmss32i.c \
../grlib/fonts/fontcmss34.c \
../grlib/fonts/fontcmss34b.c \
../grlib/fonts/fontcmss34i.c \
../grlib/fonts/fontcmss36.c \
../grlib/fonts/fontcmss36b.c \
../grlib/fonts/fontcmss36i.c \
../grlib/fonts/fontcmss38.c \
../grlib/fonts/fontcmss38b.c \
../grlib/fonts/fontcmss38i.c \
../grlib/fonts/fontcmss40.c \
../grlib/fonts/fontcmss40b.c \
../grlib/fonts/fontcmss40i.c \
../grlib/fonts/fontcmss42.c \
../grlib/fonts/fontcmss42b.c \
../grlib/fonts/fontcmss42i.c \
../grlib/fonts/fontcmss44.c \
../grlib/fonts/fontcmss44b.c \
../grlib/fonts/fontcmss44i.c \
../grlib/fonts/fontcmss46.c \
../grlib/fonts/fontcmss46b.c \
../grlib/fonts/fontcmss46i.c \
../grlib/fonts/fontcmss48.c \
../grlib/fonts/fontcmss48b.c \
../grlib/fonts/fontcmss48i.c \
../grlib/fonts/fontcmtt12.c \
../grlib/fonts/fontcmtt14.c \
../grlib/fonts/fontcmtt16.c \
../grlib/fonts/fontcmtt18.c \
../grlib/fonts/fontcmtt20.c \
../grlib/fonts/fontcmtt22.c \
../grlib/fonts/fontcmtt24.c \
../grlib/fonts/fontcmtt26.c \
../grlib/fonts/fontcmtt28.c \
../grlib/fonts/fontcmtt30.c \
../grlib/fonts/fontcmtt32.c \
../grlib/fonts/fontcmtt34.c \
../grlib/fonts/fontcmtt36.c \
../grlib/fonts/fontcmtt38.c \
../grlib/fonts/fontcmtt40.c \
../grlib/fonts/fontcmtt42.c \
../grlib/fonts/fontcmtt44.c \
../grlib/fonts/fontcmtt46.c \
../grlib/fonts/fontcmtt48.c \
../grlib/fonts/fontfixed6x8.c 

C_DEPS += \
./grlib/fonts/fontcm12.d \
./grlib/fonts/fontcm12b.d \
./grlib/fonts/fontcm12i.d \
./grlib/fonts/fontcm14.d \
./grlib/fonts/fontcm14b.d \
./grlib/fonts/fontcm14i.d \
./grlib/fonts/fontcm16.d \
./grlib/fonts/fontcm16b.d \
./grlib/fonts/fontcm16i.d \
./grlib/fonts/fontcm18.d \
./grlib/fonts/fontcm18b.d \
./grlib/fonts/fontcm18i.d \
./grlib/fonts/fontcm20.d \
./grlib/fonts/fontcm20b.d \
./grlib/fonts/fontcm20i.d \
./grlib/fonts/fontcm22.d \
./grlib/fonts/fontcm22b.d \
./grlib/fonts/fontcm22i.d \
./grlib/fonts/fontcm24.d \
./grlib/fonts/fontcm24b.d \
./grlib/fonts/fontcm24i.d \
./grlib/fonts/fontcm26.d \
./grlib/fonts/fontcm26b.d \
./grlib/fonts/fontcm26i.d \
./grlib/fonts/fontcm28.d \
./grlib/fonts/fontcm28b.d \
./grlib/fonts/fontcm28i.d \
./grlib/fonts/fontcm30.d \
./grlib/fonts/fontcm30b.d \
./grlib/fonts/fontcm30i.d \
./grlib/fonts/fontcm32.d \
./grlib/fonts/fontcm32b.d \
./grlib/fonts/fontcm32i.d \
./grlib/fonts/fontcm34.d \
./grlib/fonts/fontcm34b.d \
./grlib/fonts/fontcm34i.d \
./grlib/fonts/fontcm36.d \
./grlib/fonts/fontcm36b.d \
./grlib/fonts/fontcm36i.d \
./grlib/fonts/fontcm38.d \
./grlib/fonts/fontcm38b.d \
./grlib/fonts/fontcm38i.d \
./grlib/fonts/fontcm40.d \
./grlib/fonts/fontcm40b.d \
./grlib/fonts/fontcm40i.d \
./grlib/fonts/fontcm42.d \
./grlib/fonts/fontcm42b.d \
./grlib/fonts/fontcm42i.d \
./grlib/fonts/fontcm44.d \
./grlib/fonts/fontcm44b.d \
./grlib/fonts/fontcm44i.d \
./grlib/fonts/fontcm46.d \
./grlib/fonts/fontcm46b.d \
./grlib/fonts/fontcm46i.d \
./grlib/fonts/fontcm48.d \
./grlib/fonts/fontcm48b.d \
./grlib/fonts/fontcm48i.d \
./grlib/fonts/fontcmsc12.d \
./grlib/fonts/fontcmsc14.d \
./grlib/fonts/fontcmsc16.d \
./grlib/fonts/fontcmsc18.d \
./grlib/fonts/fontcmsc20.d \
./grlib/fonts/fontcmsc22.d \
./grlib/fonts/fontcmsc24.d \
./grlib/fonts/fontcmsc26.d \
./grlib/fonts/fontcmsc28.d \
./grlib/fonts/fontcmsc30.d \
./grlib/fonts/fontcmsc32.d \
./grlib/fonts/fontcmsc34.d \
./grlib/fonts/fontcmsc36.d \
./grlib/fonts/fontcmsc38.d \
./grlib/fonts/fontcmsc40.d \
./grlib/fonts/fontcmsc42.d \
./grlib/fonts/fontcmsc44.d \
./grlib/fonts/fontcmsc46.d \
./grlib/fonts/fontcmsc48.d \
./grlib/fonts/fontcmss12.d \
./grlib/fonts/fontcmss12b.d \
./grlib/fonts/fontcmss12i.d \
./grlib/fonts/fontcmss14.d \
./grlib/fonts/fontcmss14b.d \
./grlib/fonts/fontcmss14i.d \
./grlib/fonts/fontcmss16.d \
./grlib/fonts/fontcmss16b.d \
./grlib/fonts/fontcmss16i.d \
./grlib/fonts/fontcmss18.d \
./grlib/fonts/fontcmss18b.d \
./grlib/fonts/fontcmss18i.d \
./grlib/fonts/fontcmss20.d \
./grlib/fonts/fontcmss20b.d \
./grlib/fonts/fontcmss20i.d \
./grlib/fonts/fontcmss22.d \
./grlib/fonts/fontcmss22b.d \
./grlib/fonts/fontcmss22i.d \
./grlib/fonts/fontcmss24.d \
./grlib/fonts/fontcmss24b.d \
./grlib/fonts/fontcmss24i.d \
./grlib/fonts/fontcmss26.d \
./grlib/fonts/fontcmss26b.d \
./grlib/fonts/fontcmss26i.d \
./grlib/fonts/fontcmss28.d \
./grlib/fonts/fontcmss28b.d \
./grlib/fonts/fontcmss28i.d \
./grlib/fonts/fontcmss30.d \
./grlib/fonts/fontcmss30b.d \
./grlib/fonts/fontcmss30i.d \
./grlib/fonts/fontcmss32.d \
./grlib/fonts/fontcmss32b.d \
./grlib/fonts/fontcmss32i.d \
./grlib/fonts/fontcmss34.d \
./grlib/fonts/fontcmss34b.d \
./grlib/fonts/fontcmss34i.d \
./grlib/fonts/fontcmss36.d \
./grlib/fonts/fontcmss36b.d \
./grlib/fonts/fontcmss36i.d \
./grlib/fonts/fontcmss38.d \
./grlib/fonts/fontcmss38b.d \
./grlib/fonts/fontcmss38i.d \
./grlib/fonts/fontcmss40.d \
./grlib/fonts/fontcmss40b.d \
./grlib/fonts/fontcmss40i.d \
./grlib/fonts/fontcmss42.d \
./grlib/fonts/fontcmss42b.d \
./grlib/fonts/fontcmss42i.d \
./grlib/fonts/fontcmss44.d \
./grlib/fonts/fontcmss44b.d \
./grlib/fonts/fontcmss44i.d \
./grlib/fonts/fontcmss46.d \
./grlib/fonts/fontcmss46b.d \
./grlib/fonts/fontcmss46i.d \
./grlib/fonts/fontcmss48.d \
./grlib/fonts/fontcmss48b.d \
./grlib/fonts/fontcmss48i.d \
./grlib/fonts/fontcmtt12.d \
./grlib/fonts/fontcmtt14.d \
./grlib/fonts/fontcmtt16.d \
./grlib/fonts/fontcmtt18.d \
./grlib/fonts/fontcmtt20.d \
./grlib/fonts/fontcmtt22.d \
./grlib/fonts/fontcmtt24.d \
./grlib/fonts/fontcmtt26.d \
./grlib/fonts/fontcmtt28.d \
./grlib/fonts/fontcmtt30.d \
./grlib/fonts/fontcmtt32.d \
./grlib/fonts/fontcmtt34.d \
./grlib/fonts/fontcmtt36.d \
./grlib/fonts/fontcmtt38.d \
./grlib/fonts/fontcmtt40.d \
./grlib/fonts/fontcmtt42.d \
./grlib/fonts/fontcmtt44.d \
./grlib/fonts/fontcmtt46.d \
./grlib/fonts/fontcmtt48.d \
./grlib/fonts/fontfixed6x8.d 

OBJS += \
./grlib/fonts/fontcm12.obj \
./grlib/fonts/fontcm12b.obj \
./grlib/fonts/fontcm12i.obj \
./grlib/fonts/fontcm14.obj \
./grlib/fonts/fontcm14b.obj \
./grlib/fonts/fontcm14i.obj \
./grlib/fonts/fontcm16.obj \
./grlib/fonts/fontcm16b.obj \
./grlib/fonts/fontcm16i.obj \
./grlib/fonts/fontcm18.obj \
./grlib/fonts/fontcm18b.obj \
./grlib/fonts/fontcm18i.obj \
./grlib/fonts/fontcm20.obj \
./grlib/fonts/fontcm20b.obj \
./grlib/fonts/fontcm20i.obj \
./grlib/fonts/fontcm22.obj \
./grlib/fonts/fontcm22b.obj \
./grlib/fonts/fontcm22i.obj \
./grlib/fonts/fontcm24.obj \
./grlib/fonts/fontcm24b.obj \
./grlib/fonts/fontcm24i.obj \
./grlib/fonts/fontcm26.obj \
./grlib/fonts/fontcm26b.obj \
./grlib/fonts/fontcm26i.obj \
./grlib/fonts/fontcm28.obj \
./grlib/fonts/fontcm28b.obj \
./grlib/fonts/fontcm28i.obj \
./grlib/fonts/fontcm30.obj \
./grlib/fonts/fontcm30b.obj \
./grlib/fonts/fontcm30i.obj \
./grlib/fonts/fontcm32.obj \
./grlib/fonts/fontcm32b.obj \
./grlib/fonts/fontcm32i.obj \
./grlib/fonts/fontcm34.obj \
./grlib/fonts/fontcm34b.obj \
./grlib/fonts/fontcm34i.obj \
./grlib/fonts/fontcm36.obj \
./grlib/fonts/fontcm36b.obj \
./grlib/fonts/fontcm36i.obj \
./grlib/fonts/fontcm38.obj \
./grlib/fonts/fontcm38b.obj \
./grlib/fonts/fontcm38i.obj \
./grlib/fonts/fontcm40.obj \
./grlib/fonts/fontcm40b.obj \
./grlib/fonts/fontcm40i.obj \
./grlib/fonts/fontcm42.obj \
./grlib/fonts/fontcm42b.obj \
./grlib/fonts/fontcm42i.obj \
./grlib/fonts/fontcm44.obj \
./grlib/fonts/fontcm44b.obj \
./grlib/fonts/fontcm44i.obj \
./grlib/fonts/fontcm46.obj \
./grlib/fonts/fontcm46b.obj \
./grlib/fonts/fontcm46i.obj \
./grlib/fonts/fontcm48.obj \
./grlib/fonts/fontcm48b.obj \
./grlib/fonts/fontcm48i.obj \
./grlib/fonts/fontcmsc12.obj \
./grlib/fonts/fontcmsc14.obj \
./grlib/fonts/fontcmsc16.obj \
./grlib/fonts/fontcmsc18.obj \
./grlib/fonts/fontcmsc20.obj \
./grlib/fonts/fontcmsc22.obj \
./grlib/fonts/fontcmsc24.obj \
./grlib/fonts/fontcmsc26.obj \
./grlib/fonts/fontcmsc28.obj \
./grlib/fonts/fontcmsc30.obj \
./grlib/fonts/fontcmsc32.obj \
./grlib/fonts/fontcmsc34.obj \
./grlib/fonts/fontcmsc36.obj \
./grlib/fonts/fontcmsc38.obj \
./grlib/fonts/fontcmsc40.obj \
./grlib/fonts/fontcmsc42.obj \
./grlib/fonts/fontcmsc44.obj \
./grlib/fonts/fontcmsc46.obj \
./grlib/fonts/fontcmsc48.obj \
./grlib/fonts/fontcmss12.obj \
./grlib/fonts/fontcmss12b.obj \
./grlib/fonts/fontcmss12i.obj \
./grlib/fonts/fontcmss14.obj \
./grlib/fonts/fontcmss14b.obj \
./grlib/fonts/fontcmss14i.obj \
./grlib/fonts/fontcmss16.obj \
./grlib/fonts/fontcmss16b.obj \
./grlib/fonts/fontcmss16i.obj \
./grlib/fonts/fontcmss18.obj \
./grlib/fonts/fontcmss18b.obj \
./grlib/fonts/fontcmss18i.obj \
./grlib/fonts/fontcmss20.obj \
./grlib/fonts/fontcmss20b.obj \
./grlib/fonts/fontcmss20i.obj \
./grlib/fonts/fontcmss22.obj \
./grlib/fonts/fontcmss22b.obj \
./grlib/fonts/fontcmss22i.obj \
./grlib/fonts/fontcmss24.obj \
./grlib/fonts/fontcmss24b.obj \
./grlib/fonts/fontcmss24i.obj \
./grlib/fonts/fontcmss26.obj \
./grlib/fonts/fontcmss26b.obj \
./grlib/fonts/fontcmss26i.obj \
./grlib/fonts/fontcmss28.obj \
./grlib/fonts/fontcmss28b.obj \
./grlib/fonts/fontcmss28i.obj \
./grlib/fonts/fontcmss30.obj \
./grlib/fonts/fontcmss30b.obj \
./grlib/fonts/fontcmss30i.obj \
./grlib/fonts/fontcmss32.obj \
./grlib/fonts/fontcmss32b.obj \
./grlib/fonts/fontcmss32i.obj \
./grlib/fonts/fontcmss34.obj \
./grlib/fonts/fontcmss34b.obj \
./grlib/fonts/fontcmss34i.obj \
./grlib/fonts/fontcmss36.obj \
./grlib/fonts/fontcmss36b.obj \
./grlib/fonts/fontcmss36i.obj \
./grlib/fonts/fontcmss38.obj \
./grlib/fonts/fontcmss38b.obj \
./grlib/fonts/fontcmss38i.obj \
./grlib/fonts/fontcmss40.obj \
./grlib/fonts/fontcmss40b.obj \
./grlib/fonts/fontcmss40i.obj \
./grlib/fonts/fontcmss42.obj \
./grlib/fonts/fontcmss42b.obj \
./grlib/fonts/fontcmss42i.obj \
./grlib/fonts/fontcmss44.obj \
./grlib/fonts/fontcmss44b.obj \
./grlib/fonts/fontcmss44i.obj \
./grlib/fonts/fontcmss46.obj \
./grlib/fonts/fontcmss46b.obj \
./grlib/fonts/fontcmss46i.obj \
./grlib/fonts/fontcmss48.obj \
./grlib/fonts/fontcmss48b.obj \
./grlib/fonts/fontcmss48i.obj \
./grlib/fonts/fontcmtt12.obj \
./grlib/fonts/fontcmtt14.obj \
./grlib/fonts/fontcmtt16.obj \
./grlib/fonts/fontcmtt18.obj \
./grlib/fonts/fontcmtt20.obj \
./grlib/fonts/fontcmtt22.obj \
./grlib/fonts/fontcmtt24.obj \
./grlib/fonts/fontcmtt26.obj \
./grlib/fonts/fontcmtt28.obj \
./grlib/fonts/fontcmtt30.obj \
./grlib/fonts/fontcmtt32.obj \
./grlib/fonts/fontcmtt34.obj \
./grlib/fonts/fontcmtt36.obj \
./grlib/fonts/fontcmtt38.obj \
./grlib/fonts/fontcmtt40.obj \
./grlib/fonts/fontcmtt42.obj \
./grlib/fonts/fontcmtt44.obj \
./grlib/fonts/fontcmtt46.obj \
./grlib/fonts/fontcmtt48.obj \
./grlib/fonts/fontfixed6x8.obj 

OBJS__QUOTED += \
"grlib/fonts/fontcm12.obj" \
"grlib/fonts/fontcm12b.obj" \
"grlib/fonts/fontcm12i.obj" \
"grlib/fonts/fontcm14.obj" \
"grlib/fonts/fontcm14b.obj" \
"grlib/fonts/fontcm14i.obj" \
"grlib/fonts/fontcm16.obj" \
"grlib/fonts/fontcm16b.obj" \
"grlib/fonts/fontcm16i.obj" \
"grlib/fonts/fontcm18.obj" \
"grlib/fonts/fontcm18b.obj" \
"grlib/fonts/fontcm18i.obj" \
"grlib/fonts/fontcm20.obj" \
"grlib/fonts/fontcm20b.obj" \
"grlib/fonts/fontcm20i.obj" \
"grlib/fonts/fontcm22.obj" \
"grlib/fonts/fontcm22b.obj" \
"grlib/fonts/fontcm22i.obj" \
"grlib/fonts/fontcm24.obj" \
"grlib/fonts/fontcm24b.obj" \
"grlib/fonts/fontcm24i.obj" \
"grlib/fonts/fontcm26.obj" \
"grlib/fonts/fontcm26b.obj" \
"grlib/fonts/fontcm26i.obj" \
"grlib/fonts/fontcm28.obj" \
"grlib/fonts/fontcm28b.obj" \
"grlib/fonts/fontcm28i.obj" \
"grlib/fonts/fontcm30.obj" \
"grlib/fonts/fontcm30b.obj" \
"grlib/fonts/fontcm30i.obj" \
"grlib/fonts/fontcm32.obj" \
"grlib/fonts/fontcm32b.obj" \
"grlib/fonts/fontcm32i.obj" \
"grlib/fonts/fontcm34.obj" \
"grlib/fonts/fontcm34b.obj" \
"grlib/fonts/fontcm34i.obj" \
"grlib/fonts/fontcm36.obj" \
"grlib/fonts/fontcm36b.obj" \
"grlib/fonts/fontcm36i.obj" \
"grlib/fonts/fontcm38.obj" \
"grlib/fonts/fontcm38b.obj" \
"grlib/fonts/fontcm38i.obj" \
"grlib/fonts/fontcm40.obj" \
"grlib/fonts/fontcm40b.obj" \
"grlib/fonts/fontcm40i.obj" \
"grlib/fonts/fontcm42.obj" \
"grlib/fonts/fontcm42b.obj" \
"grlib/fonts/fontcm42i.obj" \
"grlib/fonts/fontcm44.obj" \
"grlib/fonts/fontcm44b.obj" \
"grlib/fonts/fontcm44i.obj" \
"grlib/fonts/fontcm46.obj" \
"grlib/fonts/fontcm46b.obj" \
"grlib/fonts/fontcm46i.obj" \
"grlib/fonts/fontcm48.obj" \
"grlib/fonts/fontcm48b.obj" \
"grlib/fonts/fontcm48i.obj" \
"grlib/fonts/fontcmsc12.obj" \
"grlib/fonts/fontcmsc14.obj" \
"grlib/fonts/fontcmsc16.obj" \
"grlib/fonts/fontcmsc18.obj" \
"grlib/fonts/fontcmsc20.obj" \
"grlib/fonts/fontcmsc22.obj" \
"grlib/fonts/fontcmsc24.obj" \
"grlib/fonts/fontcmsc26.obj" \
"grlib/fonts/fontcmsc28.obj" \
"grlib/fonts/fontcmsc30.obj" \
"grlib/fonts/fontcmsc32.obj" \
"grlib/fonts/fontcmsc34.obj" \
"grlib/fonts/fontcmsc36.obj" \
"grlib/fonts/fontcmsc38.obj" \
"grlib/fonts/fontcmsc40.obj" \
"grlib/fonts/fontcmsc42.obj" \
"grlib/fonts/fontcmsc44.obj" \
"grlib/fonts/fontcmsc46.obj" \
"grlib/fonts/fontcmsc48.obj" \
"grlib/fonts/fontcmss12.obj" \
"grlib/fonts/fontcmss12b.obj" \
"grlib/fonts/fontcmss12i.obj" \
"grlib/fonts/fontcmss14.obj" \
"grlib/fonts/fontcmss14b.obj" \
"grlib/fonts/fontcmss14i.obj" \
"grlib/fonts/fontcmss16.obj" \
"grlib/fonts/fontcmss16b.obj" \
"grlib/fonts/fontcmss16i.obj" \
"grlib/fonts/fontcmss18.obj" \
"grlib/fonts/fontcmss18b.obj" \
"grlib/fonts/fontcmss18i.obj" \
"grlib/fonts/fontcmss20.obj" \
"grlib/fonts/fontcmss20b.obj" \
"grlib/fonts/fontcmss20i.obj" \
"grlib/fonts/fontcmss22.obj" \
"grlib/fonts/fontcmss22b.obj" \
"grlib/fonts/fontcmss22i.obj" \
"grlib/fonts/fontcmss24.obj" \
"grlib/fonts/fontcmss24b.obj" \
"grlib/fonts/fontcmss24i.obj" \
"grlib/fonts/fontcmss26.obj" \
"grlib/fonts/fontcmss26b.obj" \
"grlib/fonts/fontcmss26i.obj" \
"grlib/fonts/fontcmss28.obj" \
"grlib/fonts/fontcmss28b.obj" \
"grlib/fonts/fontcmss28i.obj" \
"grlib/fonts/fontcmss30.obj" \
"grlib/fonts/fontcmss30b.obj" \
"grlib/fonts/fontcmss30i.obj" \
"grlib/fonts/fontcmss32.obj" \
"grlib/fonts/fontcmss32b.obj" \
"grlib/fonts/fontcmss32i.obj" \
"grlib/fonts/fontcmss34.obj" \
"grlib/fonts/fontcmss34b.obj" \
"grlib/fonts/fontcmss34i.obj" \
"grlib/fonts/fontcmss36.obj" \
"grlib/fonts/fontcmss36b.obj" \
"grlib/fonts/fontcmss36i.obj" \
"grlib/fonts/fontcmss38.obj" \
"grlib/fonts/fontcmss38b.obj" \
"grlib/fonts/fontcmss38i.obj" \
"grlib/fonts/fontcmss40.obj" \
"grlib/fonts/fontcmss40b.obj" \
"grlib/fonts/fontcmss40i.obj" \
"grlib/fonts/fontcmss42.obj" \
"grlib/fonts/fontcmss42b.obj" \
"grlib/fonts/fontcmss42i.obj" \
"grlib/fonts/fontcmss44.obj" \
"grlib/fonts/fontcmss44b.obj" \
"grlib/fonts/fontcmss44i.obj" \
"grlib/fonts/fontcmss46.obj" \
"grlib/fonts/fontcmss46b.obj" \
"grlib/fonts/fontcmss46i.obj" \
"grlib/fonts/fontcmss48.obj" \
"grlib/fonts/fontcmss48b.obj" \
"grlib/fonts/fontcmss48i.obj" \
"grlib/fonts/fontcmtt12.obj" \
"grlib/fonts/fontcmtt14.obj" \
"grlib/fonts/fontcmtt16.obj" \
"grlib/fonts/fontcmtt18.obj" \
"grlib/fonts/fontcmtt20.obj" \
"grlib/fonts/fontcmtt22.obj" \
"grlib/fonts/fontcmtt24.obj" \
"grlib/fonts/fontcmtt26.obj" \
"grlib/fonts/fontcmtt28.obj" \
"grlib/fonts/fontcmtt30.obj" \
"grlib/fonts/fontcmtt32.obj" \
"grlib/fonts/fontcmtt34.obj" \
"grlib/fonts/fontcmtt36.obj" \
"grlib/fonts/fontcmtt38.obj" \
"grlib/fonts/fontcmtt40.obj" \
"grlib/fonts/fontcmtt42.obj" \
"grlib/fonts/fontcmtt44.obj" \
"grlib/fonts/fontcmtt46.obj" \
"grlib/fonts/fontcmtt48.obj" \
"grlib/fonts/fontfixed6x8.obj" 

C_DEPS__QUOTED += \
"grlib/fonts/fontcm12.d" \
"grlib/fonts/fontcm12b.d" \
"grlib/fonts/fontcm12i.d" \
"grlib/fonts/fontcm14.d" \
"grlib/fonts/fontcm14b.d" \
"grlib/fonts/fontcm14i.d" \
"grlib/fonts/fontcm16.d" \
"grlib/fonts/fontcm16b.d" \
"grlib/fonts/fontcm16i.d" \
"grlib/fonts/fontcm18.d" \
"grlib/fonts/fontcm18b.d" \
"grlib/fonts/fontcm18i.d" \
"grlib/fonts/fontcm20.d" \
"grlib/fonts/fontcm20b.d" \
"grlib/fonts/fontcm20i.d" \
"grlib/fonts/fontcm22.d" \
"grlib/fonts/fontcm22b.d" \
"grlib/fonts/fontcm22i.d" \
"grlib/fonts/fontcm24.d" \
"grlib/fonts/fontcm24b.d" \
"grlib/fonts/fontcm24i.d" \
"grlib/fonts/fontcm26.d" \
"grlib/fonts/fontcm26b.d" \
"grlib/fonts/fontcm26i.d" \
"grlib/fonts/fontcm28.d" \
"grlib/fonts/fontcm28b.d" \
"grlib/fonts/fontcm28i.d" \
"grlib/fonts/fontcm30.d" \
"grlib/fonts/fontcm30b.d" \
"grlib/fonts/fontcm30i.d" \
"grlib/fonts/fontcm32.d" \
"grlib/fonts/fontcm32b.d" \
"grlib/fonts/fontcm32i.d" \
"grlib/fonts/fontcm34.d" \
"grlib/fonts/fontcm34b.d" \
"grlib/fonts/fontcm34i.d" \
"grlib/fonts/fontcm36.d" \
"grlib/fonts/fontcm36b.d" \
"grlib/fonts/fontcm36i.d" \
"grlib/fonts/fontcm38.d" \
"grlib/fonts/fontcm38b.d" \
"grlib/fonts/fontcm38i.d" \
"grlib/fonts/fontcm40.d" \
"grlib/fonts/fontcm40b.d" \
"grlib/fonts/fontcm40i.d" \
"grlib/fonts/fontcm42.d" \
"grlib/fonts/fontcm42b.d" \
"grlib/fonts/fontcm42i.d" \
"grlib/fonts/fontcm44.d" \
"grlib/fonts/fontcm44b.d" \
"grlib/fonts/fontcm44i.d" \
"grlib/fonts/fontcm46.d" \
"grlib/fonts/fontcm46b.d" \
"grlib/fonts/fontcm46i.d" \
"grlib/fonts/fontcm48.d" \
"grlib/fonts/fontcm48b.d" \
"grlib/fonts/fontcm48i.d" \
"grlib/fonts/fontcmsc12.d" \
"grlib/fonts/fontcmsc14.d" \
"grlib/fonts/fontcmsc16.d" \
"grlib/fonts/fontcmsc18.d" \
"grlib/fonts/fontcmsc20.d" \
"grlib/fonts/fontcmsc22.d" \
"grlib/fonts/fontcmsc24.d" \
"grlib/fonts/fontcmsc26.d" \
"grlib/fonts/fontcmsc28.d" \
"grlib/fonts/fontcmsc30.d" \
"grlib/fonts/fontcmsc32.d" \
"grlib/fonts/fontcmsc34.d" \
"grlib/fonts/fontcmsc36.d" \
"grlib/fonts/fontcmsc38.d" \
"grlib/fonts/fontcmsc40.d" \
"grlib/fonts/fontcmsc42.d" \
"grlib/fonts/fontcmsc44.d" \
"grlib/fonts/fontcmsc46.d" \
"grlib/fonts/fontcmsc48.d" \
"grlib/fonts/fontcmss12.d" \
"grlib/fonts/fontcmss12b.d" \
"grlib/fonts/fontcmss12i.d" \
"grlib/fonts/fontcmss14.d" \
"grlib/fonts/fontcmss14b.d" \
"grlib/fonts/fontcmss14i.d" \
"grlib/fonts/fontcmss16.d" \
"grlib/fonts/fontcmss16b.d" \
"grlib/fonts/fontcmss16i.d" \
"grlib/fonts/fontcmss18.d" \
"grlib/fonts/fontcmss18b.d" \
"grlib/fonts/fontcmss18i.d" \
"grlib/fonts/fontcmss20.d" \
"grlib/fonts/fontcmss20b.d" \
"grlib/fonts/fontcmss20i.d" \
"grlib/fonts/fontcmss22.d" \
"grlib/fonts/fontcmss22b.d" \
"grlib/fonts/fontcmss22i.d" \
"grlib/fonts/fontcmss24.d" \
"grlib/fonts/fontcmss24b.d" \
"grlib/fonts/fontcmss24i.d" \
"grlib/fonts/fontcmss26.d" \
"grlib/fonts/fontcmss26b.d" \
"grlib/fonts/fontcmss26i.d" \
"grlib/fonts/fontcmss28.d" \
"grlib/fonts/fontcmss28b.d" \
"grlib/fonts/fontcmss28i.d" \
"grlib/fonts/fontcmss30.d" \
"grlib/fonts/fontcmss30b.d" \
"grlib/fonts/fontcmss30i.d" \
"grlib/fonts/fontcmss32.d" \
"grlib/fonts/fontcmss32b.d" \
"grlib/fonts/fontcmss32i.d" \
"grlib/fonts/fontcmss34.d" \
"grlib/fonts/fontcmss34b.d" \
"grlib/fonts/fontcmss34i.d" \
"grlib/fonts/fontcmss36.d" \
"grlib/fonts/fontcmss36b.d" \
"grlib/fonts/fontcmss36i.d" \
"grlib/fonts/fontcmss38.d" \
"grlib/fonts/fontcmss38b.d" \
"grlib/fonts/fontcmss38i.d" \
"grlib/fonts/fontcmss40.d" \
"grlib/fonts/fontcmss40b.d" \
"grlib/fonts/fontcmss40i.d" \
"grlib/fonts/fontcmss42.d" \
"grlib/fonts/fontcmss42b.d" \
"grlib/fonts/fontcmss42i.d" \
"grlib/fonts/fontcmss44.d" \
"grlib/fonts/fontcmss44b.d" \
"grlib/fonts/fontcmss44i.d" \
"grlib/fonts/fontcmss46.d" \
"grlib/fonts/fontcmss46b.d" \
"grlib/fonts/fontcmss46i.d" \
"grlib/fonts/fontcmss48.d" \
"grlib/fonts/fontcmss48b.d" \
"grlib/fonts/fontcmss48i.d" \
"grlib/fonts/fontcmtt12.d" \
"grlib/fonts/fontcmtt14.d" \
"grlib/fonts/fontcmtt16.d" \
"grlib/fonts/fontcmtt18.d" \
"grlib/fonts/fontcmtt20.d" \
"grlib/fonts/fontcmtt22.d" \
"grlib/fonts/fontcmtt24.d" \
"grlib/fonts/fontcmtt26.d" \
"grlib/fonts/fontcmtt28.d" \
"grlib/fonts/fontcmtt30.d" \
"grlib/fonts/fontcmtt32.d" \
"grlib/fonts/fontcmtt34.d" \
"grlib/fonts/fontcmtt36.d" \
"grlib/fonts/fontcmtt38.d" \
"grlib/fonts/fontcmtt40.d" \
"grlib/fonts/fontcmtt42.d" \
"grlib/fonts/fontcmtt44.d" \
"grlib/fonts/fontcmtt46.d" \
"grlib/fonts/fontcmtt48.d" \
"grlib/fonts/fontfixed6x8.d" 

C_SRCS__QUOTED += \
"../grlib/fonts/fontcm12.c" \
"../grlib/fonts/fontcm12b.c" \
"../grlib/fonts/fontcm12i.c" \
"../grlib/fonts/fontcm14.c" \
"../grlib/fonts/fontcm14b.c" \
"../grlib/fonts/fontcm14i.c" \
"../grlib/fonts/fontcm16.c" \
"../grlib/fonts/fontcm16b.c" \
"../grlib/fonts/fontcm16i.c" \
"../grlib/fonts/fontcm18.c" \
"../grlib/fonts/fontcm18b.c" \
"../grlib/fonts/fontcm18i.c" \
"../grlib/fonts/fontcm20.c" \
"../grlib/fonts/fontcm20b.c" \
"../grlib/fonts/fontcm20i.c" \
"../grlib/fonts/fontcm22.c" \
"../grlib/fonts/fontcm22b.c" \
"../grlib/fonts/fontcm22i.c" \
"../grlib/fonts/fontcm24.c" \
"../grlib/fonts/fontcm24b.c" \
"../grlib/fonts/fontcm24i.c" \
"../grlib/fonts/fontcm26.c" \
"../grlib/fonts/fontcm26b.c" \
"../grlib/fonts/fontcm26i.c" \
"../grlib/fonts/fontcm28.c" \
"../grlib/fonts/fontcm28b.c" \
"../grlib/fonts/fontcm28i.c" \
"../grlib/fonts/fontcm30.c" \
"../grlib/fonts/fontcm30b.c" \
"../grlib/fonts/fontcm30i.c" \
"../grlib/fonts/fontcm32.c" \
"../grlib/fonts/fontcm32b.c" \
"../grlib/fonts/fontcm32i.c" \
"../grlib/fonts/fontcm34.c" \
"../grlib/fonts/fontcm34b.c" \
"../grlib/fonts/fontcm34i.c" \
"../grlib/fonts/fontcm36.c" \
"../grlib/fonts/fontcm36b.c" \
"../grlib/fonts/fontcm36i.c" \
"../grlib/fonts/fontcm38.c" \
"../grlib/fonts/fontcm38b.c" \
"../grlib/fonts/fontcm38i.c" \
"../grlib/fonts/fontcm40.c" \
"../grlib/fonts/fontcm40b.c" \
"../grlib/fonts/fontcm40i.c" \
"../grlib/fonts/fontcm42.c" \
"../grlib/fonts/fontcm42b.c" \
"../grlib/fonts/fontcm42i.c" \
"../grlib/fonts/fontcm44.c" \
"../grlib/fonts/fontcm44b.c" \
"../grlib/fonts/fontcm44i.c" \
"../grlib/fonts/fontcm46.c" \
"../grlib/fonts/fontcm46b.c" \
"../grlib/fonts/fontcm46i.c" \
"../grlib/fonts/fontcm48.c" \
"../grlib/fonts/fontcm48b.c" \
"../grlib/fonts/fontcm48i.c" \
"../grlib/fonts/fontcmsc12.c" \
"../grlib/fonts/fontcmsc14.c" \
"../grlib/fonts/fontcmsc16.c" \
"../grlib/fonts/fontcmsc18.c" \
"../grlib/fonts/fontcmsc20.c" \
"../grlib/fonts/fontcmsc22.c" \
"../grlib/fonts/fontcmsc24.c" \
"../grlib/fonts/fontcmsc26.c" \
"../grlib/fonts/fontcmsc28.c" \
"../grlib/fonts/fontcmsc30.c" \
"../grlib/fonts/fontcmsc32.c" \
"../grlib/fonts/fontcmsc34.c" \
"../grlib/fonts/fontcmsc36.c" \
"../grlib/fonts/fontcmsc38.c" \
"../grlib/fonts/fontcmsc40.c" \
"../grlib/fonts/fontcmsc42.c" \
"../grlib/fonts/fontcmsc44.c" \
"../grlib/fonts/fontcmsc46.c" \
"../grlib/fonts/fontcmsc48.c" \
"../grlib/fonts/fontcmss12.c" \
"../grlib/fonts/fontcmss12b.c" \
"../grlib/fonts/fontcmss12i.c" \
"../grlib/fonts/fontcmss14.c" \
"../grlib/fonts/fontcmss14b.c" \
"../grlib/fonts/fontcmss14i.c" \
"../grlib/fonts/fontcmss16.c" \
"../grlib/fonts/fontcmss16b.c" \
"../grlib/fonts/fontcmss16i.c" \
"../grlib/fonts/fontcmss18.c" \
"../grlib/fonts/fontcmss18b.c" \
"../grlib/fonts/fontcmss18i.c" \
"../grlib/fonts/fontcmss20.c" \
"../grlib/fonts/fontcmss20b.c" \
"../grlib/fonts/fontcmss20i.c" \
"../grlib/fonts/fontcmss22.c" \
"../grlib/fonts/fontcmss22b.c" \
"../grlib/fonts/fontcmss22i.c" \
"../grlib/fonts/fontcmss24.c" \
"../grlib/fonts/fontcmss24b.c" \
"../grlib/fonts/fontcmss24i.c" \
"../grlib/fonts/fontcmss26.c" \
"../grlib/fonts/fontcmss26b.c" \
"../grlib/fonts/fontcmss26i.c" \
"../grlib/fonts/fontcmss28.c" \
"../grlib/fonts/fontcmss28b.c" \
"../grlib/fonts/fontcmss28i.c" \
"../grlib/fonts/fontcmss30.c" \
"../grlib/fonts/fontcmss30b.c" \
"../grlib/fonts/fontcmss30i.c" \
"../grlib/fonts/fontcmss32.c" \
"../grlib/fonts/fontcmss32b.c" \
"../grlib/fonts/fontcmss32i.c" \
"../grlib/fonts/fontcmss34.c" \
"../grlib/fonts/fontcmss34b.c" \
"../grlib/fonts/fontcmss34i.c" \
"../grlib/fonts/fontcmss36.c" \
"../grlib/fonts/fontcmss36b.c" \
"../grlib/fonts/fontcmss36i.c" \
"../grlib/fonts/fontcmss38.c" \
"../grlib/fonts/fontcmss38b.c" \
"../grlib/fonts/fontcmss38i.c" \
"../grlib/fonts/fontcmss40.c" \
"../grlib/fonts/fontcmss40b.c" \
"../grlib/fonts/fontcmss40i.c" \
"../grlib/fonts/fontcmss42.c" \
"../grlib/fonts/fontcmss42b.c" \
"../grlib/fonts/fontcmss42i.c" \
"../grlib/fonts/fontcmss44.c" \
"../grlib/fonts/fontcmss44b.c" \
"../grlib/fonts/fontcmss44i.c" \
"../grlib/fonts/fontcmss46.c" \
"../grlib/fonts/fontcmss46b.c" \
"../grlib/fonts/fontcmss46i.c" \
"../grlib/fonts/fontcmss48.c" \
"../grlib/fonts/fontcmss48b.c" \
"../grlib/fonts/fontcmss48i.c" \
"../grlib/fonts/fontcmtt12.c" \
"../grlib/fonts/fontcmtt14.c" \
"../grlib/fonts/fontcmtt16.c" \
"../grlib/fonts/fontcmtt18.c" \
"../grlib/fonts/fontcmtt20.c" \
"../grlib/fonts/fontcmtt22.c" \
"../grlib/fonts/fontcmtt24.c" \
"../grlib/fonts/fontcmtt26.c" \
"../grlib/fonts/fontcmtt28.c" \
"../grlib/fonts/fontcmtt30.c" \
"../grlib/fonts/fontcmtt32.c" \
"../grlib/fonts/fontcmtt34.c" \
"../grlib/fonts/fontcmtt36.c" \
"../grlib/fonts/fontcmtt38.c" \
"../grlib/fonts/fontcmtt40.c" \
"../grlib/fonts/fontcmtt42.c" \
"../grlib/fonts/fontcmtt44.c" \
"../grlib/fonts/fontcmtt46.c" \
"../grlib/fonts/fontcmtt48.c" \
"../grlib/fonts/fontfixed6x8.c" 


